spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/offersdb
    username: hollyheroandru
    password: pgpwd4offerdb
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
